"""updated Apartment model

Revision ID: b142980d5c8f
Revises: f722308cfe4f
Create Date: 2022-09-08 11:42:00.216798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b142980d5c8f"
down_revision = "f722308cfe4f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
