version: "3"

services:
  database:
    image: "postgres:13"
    container_name: db-pg
    ports:
      - "5432:5432"

  main:
    build:
      context: .
    command: bash -c "python main.py"
    container_name: main
    volumes:
      - ./app:/app
    depends_on:
      - database