version: "3"

services:
  database:
    image: "postgres:13"
    container_name: db-pg
    env_file:
      - db_credentials.env
    ports:
      - "5432:5432"

  main:
    build:
      context: .
    command: bash -c "alembic upgrade head && python main.py"
    container_name: main
    env_file:
      - db_credentials.env
    volumes:
      - ./app:/app
    depends_on:
      - database